pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
        sh 'mvn clean install'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:19-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
