pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image '3.9.6-eclipse-temurin-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:19-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
